formulas:
  the same percentage x 100,000 sats: x*1e5
  the same percentage x 500,000 sats: x*5e5
  the same percentage x 1,000,000 sats: x*1e6
  100k sats (0.001 btc): 1e5
  0.01 btc: 1e6
  0.1 btc: 1e7
  1 btc: 1e8
exchanges:
  # - coinbase pro
  - kraken
  # - cex
trade_limits:
  kraken:
    min: 1e5
